spring.data.mongodb.uri=
spring.data.mongodb.database=carbon_tracker

# JWT Configuration
carbontracker.jwt.secret=
carbontracker.jwt.expiration=

# Server Port
server.port=8080

# OpenRouter API Configuration
openrouter.api.key=
openrouter.api.url=
openrouter.api.model=kwaipilot/kat-coder-pro
